### ISSUE TITLE
download_ortho function breaks after library is installed

### ISSUE THREAD

**Issue by alecatslalom** [nearmap/nearmap-python-api#2]
## Problem:
After installing this library via `pip install git+https://github.com/nearmap/nearmap-python-api`, I am unable to use `download_ortho` because `tile_dl.xml` is missing.

## Fix:
make sure to include the files needed to run in setup.py's `package_data` field

**Comment by geoffhtaylor** [comment]
The Nearmap-Python-Api currently only supports virtualized environment installation as it is in beta. 

pip install is not currently supported.

Please refer to the installation documentation.

https://github.com/nearmap/nearmap-python-api/tree/master/install
